// WinConst.cpp
//
// Toolbox\WinConst

module;

#include <windows.h>

module WinBasics:WinConst;

const UINT  PM_REMOVE_CONST           = PM_REMOVE;
const UINT  PM_QS_INPUT_CONST         = PM_QS_INPUT;
const UINT  CP_UTF8_CONST             = CP_UTF8;
const UINT  FIXED_PITCH_CONST         = FIXED_PITCH;
const UINT  GWL_STYLE_CONST           = GWL_STYLE;
const UINT  DM_SETDEFID_CONST         = DM_SETDEFID;

const DWORD WS_BORDER_CONST           = WS_BORDER;
const DWORD WS_CHILD_CONST            = WS_CHILD;
const DWORD WS_CLIPSIBLINGS_CONST     = WS_CLIPSIBLINGS;
const DWORD WS_CLIPCHILDREN_CONST     = WS_CLIPCHILDREN;
const DWORD WS_VISIBLE_CONST          = WS_VISIBLE;
const DWORD WS_OVERLAPPEDWINDOW_CONST = WS_OVERLAPPEDWINDOW;
const DWORD WS_OVERLAPPED_CONST       = WS_OVERLAPPED;
const DWORD WS_POPUPWINDOW_CONST      = WS_POPUPWINDOW;
const DWORD WS_POPUP_CONST            = WS_POPUP;
const DWORD WS_CAPTION_CONST          = WS_CAPTION;
const DWORD WS_SIZEBOX_CONST          = WS_SIZEBOX;
const DWORD WS_GROUP_CONST            = WS_GROUP;
const DWORD WS_TABSTOP_CONST          = WS_TABSTOP;
const DWORD WS_SYSMENU_CONST          = WS_SYSMENU;
const DWORD WS_EX_TOPMOST_CONST       = WS_EX_TOPMOST;
const DWORD WS_EX_STATICEDGE_CONST    = WS_EX_STATICEDGE;
const DWORD WS_VSCROLL_CONST          = WS_VSCROLL;
const DWORD WS_HSCROLL_CONST          = WS_HSCROLL;

const DWORD INFINITE_CONST            = INFINITE;
                                      
const DWORD SW_HIDE_CONST             = SW_HIDE;
const DWORD SW_SHOW_CONST             = SW_SHOW;
const DWORD SW_RESTORE_CONST          = SW_RESTORE;
const DWORD SW_SHOWNORMAL_CONST       = SW_SHOWNORMAL;
const DWORD SW_MAXIMIZE_CONST         = SW_MAXIMIZE;

const DWORD SB_SETTEXT_CONST          = SB_SETTEXT;
const DWORD SB_SETPARTS_CONST         = SB_SETPARTS;
                                      
const DWORD SM_CXSIZEFRAME_CONST      = SM_CXSIZEFRAME;
const DWORD SM_CYSIZEFRAME_CONST      = SM_CYSIZEFRAME;

const HWND  HWND_TOP_CONST            = HWND_TOP;
const HWND  HWND_DESKTOP_CONST        = HWND_DESKTOP;
const HWND  HWND_TOPMOST_CONST        = HWND_TOPMOST;

const DWORD SWP_NOSIZE_CONST          = SWP_NOSIZE;
const DWORD SWP_NOMOVE_CONST          = SWP_NOMOVE;
const DWORD SWP_SHOWWINDOW_CONST      = SWP_SHOWWINDOW;
                                     
const WORD  VK_SPACE_CONST            = VK_SPACE;
const WORD  VK_BACK_CONST             = VK_BACK;
const WORD  VK_DELETE_CONST           = VK_DELETE;
const WORD  VK_ESCAPE_CONST           = VK_ESCAPE;
                                     
const DWORD MF_BITMAP_CONST           = MF_BITMAP;
const DWORD MF_STRING_CONST           = MF_STRING;
const DWORD MF_BYPOSITION_CONST       = MF_BYPOSITION;
const DWORD MF_GRAYED_CONST           = MF_GRAYED;
const DWORD MF_ENABLED_CONST          = MF_ENABLED;
const DWORD MF_POPUP_CONST            = MF_POPUP;

const DWORD MB_OK_CONST               = MB_OK;
const DWORD MB_ICONWARNING_CONST      = MB_ICONWARNING;
const DWORD MB_YESNOCANCEL_CONST      = MB_YESNOCANCEL;
const DWORD MB_YESNO_CONST            = MB_YESNO;
const DWORD MB_SYSTEMMODAL_CONST      = MB_SYSTEMMODAL;
                                     
const int   IDYES_CONST               = IDYES; 
const int   IDNO_CONST                = IDNO; 
const int   IDOK_CONST                = IDOK; 
const int   IDCANCEL_CONST            = IDCANCEL; 

const int   DC_BRUSH_CONST            = DC_BRUSH; 

const DWORD MK_SHIFT_CONST            = MK_SHIFT;
const DWORD MK_CONTROL_CONST          = MK_CONTROL;
const DWORD MK_LBUTTON_CONST          = MK_LBUTTON;
  
const DWORD BM_SETSTYLE_CONST         = BM_SETSTYLE;

const DWORD BS_PUSHBUTTON_CONST       = BS_PUSHBUTTON;
const DWORD BS_DEFPUSHBUTTON_CONST    = BS_DEFPUSHBUTTON;
const DWORD BS_AUTOCHECKBOX_CONST     = BS_AUTOCHECKBOX;
const DWORD BS_OWNERDRAW_CONST        = BS_OWNERDRAW;
                                     
const DWORD CS_OWNDC_CONST            = CS_OWNDC;
const DWORD CS_HREDRAW_CONST          = CS_HREDRAW;
const DWORD CS_VREDRAW_CONST          = CS_VREDRAW;
const DWORD CS_DBLCLKS_CONST          = CS_DBLCLKS;

const DWORD CW_USEDEFAULT_CONST       = CW_USEDEFAULT;

const DWORD DT_LEFT_CONST             = DT_LEFT;

const DWORD EN_CHANGE_CONST           = EN_CHANGE;
const DWORD EM_GETSEL_CONST           = EM_GETSEL;
const DWORD EM_SETSEL_CONST           = EM_SETSEL;
const DWORD EM_GETLINECOUNT_CONST     = EM_GETLINECOUNT;

const DWORD ES_LEFT_CONST             = ES_LEFT;
const DWORD ES_RIGHT_CONST            = ES_RIGHT;
const DWORD ES_MULTILINE_CONST        = ES_MULTILINE;  
const DWORD ES_WANTRETURN_CONST       = ES_WANTRETURN; 
const DWORD ES_AUTOHSCROLL_CONST      = ES_AUTOHSCROLL;
const DWORD ES_AUTOVSCROLL_CONST      = ES_AUTOVSCROLL;

const DWORD TA_CENTER_CONST           = TA_CENTER;
const DWORD TA_LEFT_CONST             = TA_LEFT;
const DWORD TA_RIGHT_CONST            = TA_RIGHT;
                  
const DWORD TME_HOVER_CONST           = TME_HOVER;
const DWORD TME_LEAVE_CONST           = TME_LEAVE;
const DWORD TBM_GETPOS_CONST          = TBM_GETPOS;
const DWORD TBM_SETRANGEMIN_CONST     = TBM_SETRANGEMIN;
const DWORD TBM_SETRANGEMAX_CONST     = TBM_SETRANGEMAX;
const DWORD TBS_NOTICKS_CONST         = TBS_NOTICKS;
const DWORD TPM_TOPALIGN_CONST        = TPM_TOPALIGN; 
const DWORD TPM_LEFTALIGN_CONST       = TPM_LEFTALIGN;
const DWORD TPM_RETURNCMD_CONST       = TPM_RETURNCMD;
const DWORD TPM_NONOTIFY_CONST        = TPM_NONOTIFY;
const DWORD TMPF_FIXED_PITCH_CONST    = TMPF_FIXED_PITCH;

const DWORD DS_CENTER_CONST           = DS_CENTER;
const DWORD DS_MODALFRAME_CONST       = DS_MODALFRAME;
const DWORD DS_SHELLFONT_CONST        = DS_SHELLFONT;

const BYTE  FVIRTKEY_CONST            = FVIRTKEY; 
const BYTE  FCONTROL_CONST            = FCONTROL; 
const BYTE  FALT_CONST                = FALT; 

const LPCWSTR IDC_SIZENS_CONST        = IDC_SIZENS;
const LPCWSTR IDC_SIZEWE_CONST        = IDC_SIZEWE;
const LPCWSTR IDC_WAIT_CONST          = IDC_WAIT; 
const LPCWSTR IDC_ARROW_CONST         = IDC_ARROW;

const int EXCEPTION_EXECUTE_HANDLER_CONST = EXCEPTION_EXECUTE_HANDLER;
